name: Release to PyPI

on:
  release:
    types: [released]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install poetry
        run: pip install poetry poetry-dynamic-versioning
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: poetry
          cache-dependency-path: pyproject.toml
      - name: Install dependencies
        run: make setup
      - name: Publish to PyPI
        run: |
          poetry publish --build -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
